image: maven:3.3.9-jdk-8

java:
  tags:
    - meindl.dev
  stage: test
  script:
  - mvn verify
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml
